#!/bin/sh
# mus - wrapper around mpc
# this file in public domain

cmd="$1"
shift
case "$cmd" in
toggle|pause)
	mpc toggle
	;;
stop)
	mpc stop
	;;
prev)
	mpc cdprev
	;;
next)
	mpc next
	;;
play)
	if [ $# -eq 0 ]
	then
		mpc play
		mpc playlist
	else
		mpc searchplay any $(echo "$*" | sed 's/[     ][^     ]/ any&/g')
	fi
	;;
search)
	mpc search any $(echo "$*" | sed 's/[     ][^     ]/ any&/g')
	;;
playlist)
	if [ $# -eq 0 ]
	then
		mpc lsplaylists
	else
		mpc clear
		mpc load "$*"
		mpc play
	fi
	;;
help)
	printf "toggle\tToggle play/pause\n"
	printf "stop\tStop playback\n"
	printf "prev\tPlay the previous song in the queue\n"
	printf "next\tPlay the next song in the queue\n"
	printf "search\tSearch for a song\n"
	printf "play\tList songs or select song\n"
	printf "playlist\tList playlist or select playlist\n"
	;;
esac
