.TH MUS 1
.SH NAME
wm \- control the active window
.SH SYNOPSIS
.B wm
.RI [ command ]
.SH DESCRIPTION
.B scrot
is a wrapper around wmctrl(1).
It has a few commands.
.PP
The commands are as follows:
.TP
.B move
Move and resize the active window by drawing on the screen its position and size.
.TP
.B resize
Same as
.B move
.TP
.B maximize
Maximize the active window
.TP
.B minimize
Minimize the active window
.TP
.B close
Close the active window
.SH SEE ALSO
.IR wmctrl (1)
